#Custom properties file
#Fri Jun 08 10:58:07 CEST 2018
database.name=bsbm10m
saturation.enable=true
dictionary.fetch_size=1000
database.port=5432
database.user=postgres
statistics.create_tables_flag=false
saturation.batch_size=1000
database.engine=POSTGRESQL
database.dictionary_table_name=dictionary
database.triples_table_name=triples
database.password=postgres
database.drop_existing_db=true
database.storage_layout=TRIPLES_TABLE
database.encoded_triples_table_name=encoded_triples
database.host=localhost
database.encoded_saturated_triples_table_name=encoded_saturated_triples
