database.engine = POSTGRESQL
database.host = localhost
database.port = 5432
database.name = myanotheranotherrdfdb
database.user = postgres
database.password =

database.triples_table_name = tmp_triples
database.encoded_triples_table_name = tmp_encoded
database.dictionary_table_name = dictionary
database.storage_layout = TRIPLES_TABLE
database.drop_existing_db = true

saturation.batch_size = 1000
saturation.enable = true
database.encoded_saturated_triples_table_name = tmp_encoded_saturated
