####################################################################################################
#                                                                                                  #
#                                   DO NOT COMMIT LOCAL (TEST) CHANGES                             #
#                                                                                                  #
####################################################################################################

#+++++++++++++++++++++++++++++++ UNDERLYING RDBMS ENGINE PROPERTIES +++++++++++++++++++++++++++++++#
# Database engine
#database.engine = MYSQL
database.engine = POSTGRESQL
# Database host
database.host = localhost
# Database port
database.port = 5432
#database.port = 3306
# Database name: if you don't specify the database name, all tables will be created 
# in the default database (called postgres for PostgreSQL).
database.name = qstest
# Database user
database.user = postgres
#database.user = cedar
# Database password
database.password = postgres
#database.password = cedar

# The RDBMS (input) triples table name
database.triples_table_name = triples

# The RDBMS (output) encoded triples table name
database.encoded_triples_table_name = encoded_triples

# Database dictionary table name.
# Use to encode the input query and ontology and decode the results.
database.dictionary_table_name = dictionary

# Database (physical) storage layout.
# Valid options: TRIPLES_TABLE, TABLE_PER_ROLE_AND_CONCEPT
database.storage_layout = TRIPLES_TABLE
#database.storage_layout = TABLE_PER_ROLE_AND_CONCEPT

# If this parameter is true and if there already exists a database of the given name, 
# then the database is dropped before being rewritten.
database.drop_existing_db = true
# If this parameter is true and if there already exist tables (within the database of the given name)
# having the name of some tables that we want to create, then these tables are dropped before being
# recreated.
#++++++++++++++++++++++++++++++++++++++ DICTIONARY PROPERTIES +++++++++++++++++++++++++++++++++++++#
# Dictionary resultSet fetch size.
dictionary.fetch_size = 1000
#+++++++++++++++++++++++++++++++++++++ SATURATION PROPERTIES ++++++++++++++++++++++++++++++++++++++#
# Batch size.
saturation.batch_size = 1000
# Enable/disable saturation
saturation.enable = true
# default name: encoded_saturated_triples
database.encoded_saturated_triples_table_name = encoded_saturated_triples
#++++++++++++++++++++++++++++++++++++++ STATISTICS PROPERTIES +++++++++++++++++++++++++++++++++++++#
# Flag indicating the statistics tables generation (or not) for the triples table.
statistics.create_tables_flag = false
