database.dictionary_table_name=dictionary
database.drop_existing_db=true
database.encoded_saturated_triples_table_name=encoded_saturated_triples
database.encoded_triples_table_name=encoded_triples
database.host=localhost
database.name=
database.password=postgres
database.port=5432
database.storage_layout=TRIPLES_TABLE
database.triples_table_name=triples
database.user=postgres
dataset.filename=test.nt
dictionary.fetch_size=1000
saturation.batch_size=1000
saturation.enable=false
statistics.create_tables_flag=false
statistics.export_to_csv_file=true