## This prefix will be used for all the URIs of nodes created by summarization
prefixURIForSummaryNodes = http://quotientsummary.org/
## This URI will be used as a property, to denote the number of graph nodes represented by a given summary node
summaryNodeSupportURI = http://quotientsummary.org/nodeSupport
## This URI will be used as a property, to denote the number of graph edges represented by a given summary edge
summaryEdgeSupportURI = http://quotientsummary.org/edgeSupport
## This prefix will be used to assign URIs (through reification) to summary edges
reifiedSummaryEdgeURIPrefix = http://quotientsummary.org/edge
## The next three URIs will be used to describe reified summary edges, in order to state their support
reifiedEdgeHasSubject = http://quotientsummary.org/reifiedEdgeSubject
reifiedEdgeHasProperty = http://quotientsummary.org/reifiedEdgeProperty
reifiedEdgeHasObject = http://quotientsummary.org/reifiedEdgeObject
